settings:
  filament_detection:
    label: Filament Detection
    items:
      system:
        label: Filament Tag Detection System for Internal Readers
        description: External system adds support for extra tag types, like Bambu/Creality/Anycubic/Elegoo tagged spools.
        get_cmd:
          - bash
          - -c
          - if test -f /oem/printer_data/config/extended/filament-detect/base.cfg; then echo external; elif test -f /oem/printer_data/config/extended/klipper/disable-rfid-reader.cfg; then echo none; else echo official; fi
        options:
          none:
            label: None
            cmd:
              - bash
              - -xc
              - |
                ln -sf /usr/local/share/firmware-config/tweaks/klipper/disable-rfid-reader.cfg /oem/printer_data/config/extended/klipper/disable-rfid-reader.cfg
                rm -vf /oem/printer_data/config/extended/filament-detect/base.cfg
                /etc/init.d/S99filament-detect stop
                /etc/init.d/S60klipper restart         
          official:
            label: Snapmaker
            cmd:
              - bash
              - -xc
              - |
                rm -vf /oem/printer_data/config/extended/klipper/disable-rfid-reader.cfg
                rm -vf /oem/printer_data/config/extended/filament-detect/base.cfg
                /etc/init.d/S99filament-detect stop
                /etc/init.d/S60klipper restart
          external:
            label: External/Sims
            cmd:
              - bash
              - -xc
              - |
                ln -sf /usr/local/share/firmware-config/tweaks/klipper/disable-rfid-reader.cfg /oem/printer_data/config/extended/klipper/disable-rfid-reader.cfg
                ln -sf /usr/local/share/firmware-config/tweaks/filament-detect/base.cfg /oem/printer_data/config/extended/filament-detect/base.cfg
                /etc/init.d/S99filament-detect start
                /etc/init.d/S60klipper restart
                echo Please read the relevant documentation for this feature. Bambu Lab and Creality spools are not enabled by default.
        default: official
      generic:
        label: Label All Filament as Generic
        description: Snapmaker Orca hides all filament no matching profile could be found for. As the Generic profile is always present, this will garuantee it shows up. Only works when detection system is set to 'External/Sims'
        get_cmd:
          - bash
          - -c
          - test -f /oem/printer_data/config/extended/filament-detect/success_exporter_generic.cfg && echo true || echo false
        options:
          "true":
            label: Enabled
            cmd:
              - bash
              - -xc
              - |
                rm -vf /oem/printer_data/config/extended/filament-detect/success_exporter.cfg
                ln -sf /usr/local/share/firmware-config/tweaks/filament-detect/success_exporter_generic.cfg /oem/printer_data/config/extended/filament-detect/success_exporter_generic.cfg
                /etc/init.d/S99filament-detect restart
          "false":
            label: Disabled
            cmd:
              - bash
              - -xc
              - |
                rm -vf /oem/printer_data/config/extended/filament-detect/success_exporter_generic.cfg
                ln -sf /usr/local/share/firmware-config/tweaks/filament-detect/success_exporter.cfg /oem/printer_data/config/extended/filament-detect/success_exporter.cfg
                /etc/init.d/S99filament-detect restart
        default: "false"
